package com.oc.boot.portal.bean;

import java.util.Date;

public class ConstsSiteCarousel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.picture
     *
     * @mbg.generated
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.enable
     *
     * @mbg.generated
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consts_site_carousel.del
     *
     * @mbg.generated
     */
    private Boolean del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.id
     *
     * @return the value of t_consts_site_carousel.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.id
     *
     * @param id the value for t_consts_site_carousel.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.name
     *
     * @return the value of t_consts_site_carousel.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.name
     *
     * @param name the value for t_consts_site_carousel.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.picture
     *
     * @return the value of t_consts_site_carousel.picture
     *
     * @mbg.generated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.picture
     *
     * @param picture the value for t_consts_site_carousel.picture
     *
     * @mbg.generated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.url
     *
     * @return the value of t_consts_site_carousel.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.url
     *
     * @param url the value for t_consts_site_carousel.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.weight
     *
     * @return the value of t_consts_site_carousel.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.weight
     *
     * @param weight the value for t_consts_site_carousel.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.enable
     *
     * @return the value of t_consts_site_carousel.enable
     *
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.enable
     *
     * @param enable the value for t_consts_site_carousel.enable
     *
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.create_time
     *
     * @return the value of t_consts_site_carousel.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.create_time
     *
     * @param createTime the value for t_consts_site_carousel.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.create_user
     *
     * @return the value of t_consts_site_carousel.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.create_user
     *
     * @param createUser the value for t_consts_site_carousel.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.update_time
     *
     * @return the value of t_consts_site_carousel.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.update_time
     *
     * @param updateTime the value for t_consts_site_carousel.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.update_user
     *
     * @return the value of t_consts_site_carousel.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.update_user
     *
     * @param updateUser the value for t_consts_site_carousel.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consts_site_carousel.del
     *
     * @return the value of t_consts_site_carousel.del
     *
     * @mbg.generated
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consts_site_carousel.del
     *
     * @param del the value for t_consts_site_carousel.del
     *
     * @mbg.generated
     */
    public void setDel(Boolean del) {
        this.del = del;
    }
}