package com.oc.boot.portal.dao;

import com.oc.boot.portal.bean.AuthUser;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AuthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbg.generated
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbg.generated
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbg.generated
     */
    AuthUser selectByPrimaryKey(Integer id);


    List<AuthUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthUser record);
}