package com.oc.boot.portal.dao;

import com.oc.boot.portal.bean.ConstsSiteCarousel;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ConstsSiteCarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_site_carousel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_site_carousel
     *
     * @mbg.generated
     */
    int insertSelective(ConstsSiteCarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_site_carousel
     *
     * @mbg.generated
     */
    ConstsSiteCarousel selectByPrimaryKey(Integer id);

    List<ConstsSiteCarousel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_site_carousel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConstsSiteCarousel record);

}