package com.oc.boot.portal.dao;

import com.oc.boot.portal.bean.ConstsClassify;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ConstsClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_classify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_classify
     *
     * @mbg.generated
     */
    int insert(ConstsClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_classify
     *
     * @mbg.generated
     */
    int insertSelective(ConstsClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_classify
     *
     * @mbg.generated
     */
    ConstsClassify selectByPrimaryKey(Integer id);


    List<ConstsClassify> selectByParentCode(String parentCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_classify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConstsClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consts_classify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConstsClassify record);
}